print("\n\tTu promedio de 5 numeros\n")
A = float(input("Ingrese el primer numero: "))
B = float(input("Ingrese el segundo numero: "))
C = float(input("Ingrese el tercer numero: "))
D = float(input("Ingrese el cuarto numero: "))
E = float(input("Ingrese el quito numero: "))
promedio = ((A+B+C+D+E)/5)
print("\nSu promedio es:",promedio)